---
abstract: 'Nephia plugin that provides DSL for using PocketIO'
author:
  - 'ytnobody / satoshi azuma <ytnobody@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.5, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nephia-Plugin-PocketIO
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Nephia::Plugin::PocketIO:
    file: lib/Nephia/Plugin/PocketIO.pm
    version: 0.03
requires:
  HTML::Escape: 0
  Nephia: 0
  Plack::Handler::Twiggy: 0
  PocketIO: 0
  Sub::Recursive: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/ytnobody/Nephia-Plugin-PocketIO/issues
  homepage: https://github.com/ytnobody/Nephia-Plugin-PocketIO
  repository: git://github.com/ytnobody/Nephia-Plugin-PocketIO.git
version: 0.03
